### PR TITLE
Make really big arrays not panic bytebeat::compile()

### LINKED ISSUE #65: Crash on really big arrays
The fuzzer found the following test case: `73700 [000000 [000000000013349110587049772416 [000000 [00000086`

I was able to reduce to the following: `[9223372036854775809` (note, this is equal to `i64::MAX + 2`).

The following error also occurs.
`thread '<unnamed>' panicked at 'attempt to subtract with overflow', /[snip]/src/lib.rs:334:35`

The problem appears to be this line in lib.rs:
https://github.com/a2aaron/bytebot/blob/52d2cd382cadaa02719bf83e42b2a1152ece39a8/src/lib.rs#L95

The `Arr(x) => -(x as isize)` will underflow due to the cast to `isize`, and then become very positive (`9223372036854775807`). This incorrectly makes `compile()` believe the stack is now very big, and thus it will compile since `stack_size` is basically infinite.

----

There is also this test case I found: `[9223372036854775808` (note, this is equal to `i64::MAX + 1`)

The problem is the same line, but the crash is `thread 'main' panicked at 'attempt to negate with overflow', src/lib.rs:95:23`

Here, `9223372036854775808 as isize = -9223372036854775808`

Note: I believe on my computer, `isize == i64`, but I'm not sure how to check.

In both of these cases, we should properly reject these arrays as underflowing the stack, that or reject them at parsing time as `BadArr`s

### PR DESCRIPTION
**Pull request by a2aaron**
Really big arrays (ones whose size are larger than an isize) would cause
a panic due to isize overflows. This commit now forces these mega arrays
to saturate to `isize::max_value()` (this won't work for any arrays larger than a usize, but
I'm less worried about that since these arrays are still very very large).

Resolves #65

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -92,7 +92,7 @@ pub fn compile(cmds: Vec<Cmd>) -> Result<Program, CompileError> {
             // then pops x more values off the stack. Finally, it
             // pushes one value back onto the stack based on the index
             // Thus the net effect of Arr is to reduce the stack size by x.
-            Arr(x) => -(x as isize),
+            Arr(x) => -saturating_as_isize(x),
```
Comment (porglezomp) [inline src/lib.rs:95]: This is fine since we'll only lose information about arrays with more that 2^63 elements on them, which isn't practical…

**Review by porglezomp — APPROVED** [review]
Looks good
