### PR TITLE
Fix Overflow/Underflow bug

### LINKED ISSUE #11: Make operations not panic due to integer under/overflow.
Currently, Rust panics due to `attempt to multiply/add/subtract/etc with overflow.` This can be fixed using `wrapping_mul` or other similar functions.

### PR DESCRIPTION
**Pull request by a2aaron**
Fixes #11

### CODE REVIEW

File: src/lib.rs [hunk 1]
```diff
@@ -50,7 +50,7 @@ pub fn eval_beat(cmds: &[Cmd], t: i32) -> Result<i32, ()> {
                 if b == 0 {
                     stack.push(0);
                 } else {
-                    stack.push(a % b);
+                    stack.push(a.wrapping_rem(b));
```
Comment (porglezomp) [inline src/lib.rs:53]: Oh, I missed this one in mine, good work.

File: src/lib.rs [hunk 2]
```diff
@@ -23,25 +23,25 @@ pub fn eval_beat(cmds: &[Cmd], t: i32) -> Result<i32, ()> {
...
+                stack.push(a.wrapping_mul(b));
             }
             Cmd::Div => {
                 let b = stack.pop().ok_or(())?;
                 let a = stack.pop().ok_or(())?;
                 if b == 0 {
                     stack.push(0);
                 } else {
-                    stack.push(a / b);
+                    stack.push(a.wrapping_div(b));
```
Comment (porglezomp) [inline src/lib.rs:44]: This is good for symmetry, and I did it also, but I'm suspicious that this probably is unnecessary/does nothing.

**Review by porglezomp — APPROVED** [review]
LGTM
